### ISSUE TITLE
Allow to use another DBMS

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-api#10]
See the initial intention behind https://github.com/codegouvfr/sill-api/issues/5 and the distinction between enhancing the currnet git-based setup, and the use of another DBMS for _ease of deployment_ and (perhaps) maintenance.

Let's keep track of DBMS considerations here for @JeromeBu who might also chime in.

**Comment by garronej** [comment]
Having an other system for persistance than the git data repo is quite easy. It can be done simply by implementing an other adapter for the [DbApi](https://github.com/codegouvfr/sill-api/blob/550806291e5afe95010932e8c8c1ce2f3074acda/src/core/ports/DbApi.ts#L3-L8) port.

Maybe ther's no need to involve an actual DBMS. Simply writing/reading data from a large local JSON file could suffice. Alternatively, SQLite could also be a great option.

Regarding ease of deployment, if it's a concern, writing a Docker Compose file would be crucial. It would be much more inpactfull to that regard than having an other option for persistance.

However, I want to emphasize that performance of the GIT based persistance layer is now a non-issue.

**Comment by bzg** [comment]
Points taken, thanks! I'll summarize them in a separate, more generic issue about the whole application.

**Comment by JeromeBu** [comment]
what do you think about keeping all the issues in the sill-web repo ? I almost miss this one

**Comment by JeromeBu** [comment]
I see another issue has been created on sill-web, I reference it here for follow up 
https://github.com/codegouvfr/sill-web/issues/101

**Comment by bzg** [comment]
I'm closing this one as the conversation continues on sill-web.
