### ISSUE TITLE
Outdated minimal version for SPIP

### ISSUE THREAD

**Issue by bzg** [codegouvfr/sill-api#9]
https://www.wikidata.org/wiki/Q1536426 indicates the last version correctly but https://code.gouv.fr/sill/detail?name=SPIP does not (see [this message](https://social.numerique.gouv.fr/@zzzazzz@mastodon.social/111382018506399286)).

I expected the SILL API to update release informations regularily, isn't it the case?

**Comment by garronej** [comment]
Well, the "Minimum Required Version" is not the "latest version." The "Minimum Required Version" is determined by the maintainer and is intended to be manually updated. It represents the oldest version that is considered acceptable for production use if you are using this software in the context of public services.

The "latest version" is regularly updated by SILL, as illustrated in this view, which displays the software sorted by the most recent update release: https://code.gouv.fr/sill/list?sort=latest_version_publication_date

The SILL determines the latest version based on tag name inferences. If we have a repository URL that is a GitHub repository for software, we can infer the latest version. However, if the repository is hosted elsewhere, such as the case with PSIP, which is on GitLab (https://git.spip.net/spip/spip), we are unable to do so. Acquiring all the tags would require cloning the repository, which would be resource-intensive this is why we levrage GitHub API. Many repositories are quite large. Surprisingly, it's not feasible to retrieve only the latest tag of a repository—we must fetch all the tags and then apply semantic versioning logic to determine the latest one.

It would be beneficial to update the function that retrieves the latest version to check Wikidata for the information before defaulting to inferring from the Git tags.

**Comment by bzg** [comment]
Thanks a lot for the thorough feedback. I agree checking both Wikidata then GitHub (in this order) would be good.

Perhaps Software Heritage [API](https://archive.softwareheritage.org/api/1/) can somehow help to let us retrieve the latest tag for each repo? Ping'ing @hjonin in case she explored this already.

If not, I wonder how difficult (and useful) this would be to simply have a process (distinct from the SILL app) that clones repos, fetches the latest tag and expose this in a minimal json file somewhere. It looks both stupid and useful. Just thinking out loud.

**Comment by bzg** [comment]
I've manually updated the "latest required version" for [SPIP](https://code.gouv.fr/sill/detail?name=SPIP) to "Dernière stable". I will open another, more specific issue.

**Comment by bzg** [comment]
I'm closing this issue - follow up on https://github.com/codegouvfr/sill-api/issues/18
